[package]
name = "quadtree"
version = "0.1.0"
authors = ["Kim Nilsson <kim@wayoftao.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
smallvec = "^1.6.1"
stable-vec = "^0.4.0"
num-traits = "^0.2.14"
